#ifndef PIN_ASSIGN_H
#define PIN_ASSIGN_H

#define LEFT_MOTOR_PWM_PIN 5
#define RIGHT_MOTOR_PWM_PIN 6

#define LEFT_MOTOR_DIR_PIN 2
#define RIGHT_MOTOR_DIR_PIN 4

#define SERVO_PIN 10

#define TRIGGER_PIN 12
#define ECHO_PIN 13

#endif // PIN_ASSIGN_H
